version: '3.9'
services:
  gateway:
    build:
      dockerfile: docker/gateway/nginx/Dockerfile
    ports:
      - "80:8080"
      - "8081:8081"
    depends_on:
      - web
      - api
      - mysql
  web:
    build:
      dockerfile: docker/frontend/nginx/Dockerfile
    volumes:
      - ./app:/app
  php-fpm:
    build:
      dockerfile: docker/backend/php-fpm/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - redis
      - mysql
  php-cli:
    build:
      context: docker/
      dockerfile: backend/php-cli/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - redis
      - mysql
  api:
    build:
      dockerfile: docker/backend/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - php-fpm
  redis:
    build:
      dockerfile: docker/redis/Dockerfile
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /docker/redis:/usr/local/etc/redis
  mysql:
      image: mysql:5.7
      cap_add:
        - SYS_NICE
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      restart: always
      ports:
        - '3306:3306'
      volumes:
        - /docker/backend/mysql:/var/lib/mysql


